.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH set 1  "set " 
.SH NAME
set \- Set device brightness, either absolute (300), as percentage of the devices maximum (50%) or relative to the current value (+10, \-5%)
.SH SYNOPSIS
\fBset\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVALUE\fR> 
.SH DESCRIPTION
Set device brightness, either absolute (300), as percentage of the devices maximum (50%) or relative to the current value (+10, \-5%)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVALUE\fR>

